---
- hosts: all
  become: yes
  tasks:
    - name: i want to install apache2
      apt: apache2
      state: present

    - name: start apache2
      service:
       name: apache2
       state: restart